ASP.NetCV/ASP.NetCV/Controllers/ContactController.cs
using ASP.NetCV.Models.DataContext;
using ASP.NetCV.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NetCV.Controllers
{
    public class ContactController : Controller
    {
        readonly CvDbContext db;
        public ContactController(CvDbContext db)
        {
            this.db = db;
        }
        [HttpGet]
        public IActionResult ContactUs()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ContactUs(ContactPost model)
        {
            if (ModelState.IsValid)
            {
                db.Add(model);
                db.SaveChanges();
                return Json(new
                {
                    error = false,
                    message = "Sizin muracietiniz qeyde alindi"

                });
            }

            return Json(new
            {
                error = true,
                message = "Sizin muracietiniz qeyde alinmadi,zehmet olmasa yeniden yoxlayin"

            });
        }
            
        


    }
}

ASP.NetCV/ASP.NetCV/Controllers/PortfolioController.cs
using ASP.NetCV.Models.DataContext;
using ASP.NetCV.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NetCV.Controllers
{
    public class PortfolioController : Controller
    {
        readonly CvDbContext db;
        public PortfolioController(CvDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            var data = db.Portfolios.Where(p => p.DeletedByUserID == null).ToList();
            return View(data);
        }
    }
}

ASP.NetCV/ASP.NetCV/Controllers/ResumeController.cs
using ASP.NetCV.Models.DataContext;
using ASP.NetCV.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NetCV.Controllers
{
    public class ResumeController : Controller
    {
        readonly CvDbContext db;
        public ResumeController(CvDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            Resume resume = new Resume();
            resume.Bio = db.BioSkilsInfos.FirstOrDefault(b => b.DeletedByUserID == null);
            resume.ResumeSkils = db.ResumeSkils.Where(b => b.DeletedByUserID == null).ToList();
            resume.Expirences = db.Expirences.Where(b => b.DeletedByUserID == null).ToList(); 
            resume.ResumeBackgrounds = db.ResumeBackgrounds.Where(b => b.DeletedByUserID == null).ToList();
            return View(resume);
        }
    }
}

ASP.NetCV/ASP.NetCV/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="M_Adnan" />
    <!-- Document Title -->
    <title>Resume / CV HTML5 Template</title>

    <!-- StyleSheets -->
    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/main.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    @RenderSection("addcss", required: false)

    <!-- FontsOnline -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <!-- JavaScripts -->
    <script src="~/assets/js/vendors/modernizr.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>
<body>

    <!-- Page Wrapper -->
    <div id="wrap">

        <!-- Header -->
        <nav id="cd-lateral-nav">

            <h5 class="tittle">Latest Post</h5>
            <ul class="latest-post">

                <!-- Post Small -->
                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">
                                Hello Itaewon
                                Project
                            </a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
                <!-- Post Small -->
                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img-1.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">Casual in grey</a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
                <!-- Post Small -->
                <li>
                    <div class="media">
                        <div class="media-left"> <a href="#."><img src="~/uploads/images/small-img-2.jpg" alt=""></a></div>
                        <div class="media-body">
                            <a href="#.">Transittions</a>
                            <p class="font-crimson font-italic">Webdesign</p>
                        </div>
                    </div>
                </li>
            </ul>
        </nav>

        <!-- End Header -->
        <!-- Content -->
        <main class="cd-main-content">
            <div id="content">
                <div class="resume">
                    <nav>
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-tabis" aria-expanded="false"> <span class="tittle">MENU</span> <span class="fa fa-navicon icon-nav"></span> </button>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="nav-tabis">
                            <ul class="isop-filter main-nav">
                                <li class="active"><a asp-controller="about" asp-action="index"><i class="icon-user"></i> ABOUT ME</a></li>
                                <li><a asp-controller="Resume" asp-action="Index"><i class="icon-book-open"></i>RESUME</a></li>
                                <li><a asp-controller="Portfolio" asp-action="Index"><i class="icon-rocket"></i>PORTFOLIO</a></li>
                                <li><a asp-controller="blog" asp-action="Index"><i class="icon-note"></i>BLOG</a></li>
                                <li><a asp-controller="Contact" asp-action="ContactUs"><i class="icon-pencil"></i>CONTACT ME</a></li>

                            </ul>
                        </div>
                    </nav>
                    <div class="container">

                        <!-- TOP HEAD -->
                        <div class="top-head">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h4>Resume </h4>
                                    <a asp-controller="about" asp-action="edit">Edit Resume</a>
                                </div>
                                <div class="col-sm-6">
                                    @if (User.Identity.IsAuthenticated)
                                    {

                                        <p class="login100-form">@User.GetPrinciplesName()</p>
                                    }
                                </div>
                            </div>
                        </div>

                        <!-- Resume -->
                        <div class="row">
                            <!-- Sidebar -->
                            <div class="col-md-4">
                                <div class="side-bar">

                                    <!-- Professional Details -->
                                    <h5 class="tittle">Professional Details</h5>
                                    <img src="~/uploads/images/avatar.jpg" class="img-responsive" alt="">
                                    @await Component.InvokeAsync("UserInfo")


                                    <!-- Attachments -->
                                    <h5 class="tittle">Attachments</h5>
                                    <div class="attach bor-btm padding-25">
                                        <ul>
                                            <li>
                                                <p><img src="~/uploads/images/pdf-icon.jpg" alt=""> Curriculum-Vitae.pdf <a href="#."><i class="fa fa-cloud-download"></i></a> <a href="#."><i class="fa fa-eye"></i></a></p>
                                            </li>
                                            <li>
                                                <p><img src="~/uploads/images/word-icon.jpg" alt=""> COE.docx <a href="#."><i class="fa fa-cloud-download"></i></a> <a href="#."><i class="fa fa-eye"></i></a></p>
                                            </li>
                                        </ul>
                                    </div>

                                    <!-- Social Profiles -->
                                    <h5 class="tittle">Social Profiles</h5>
                                    <div class="social-icon bor-btm padding-25">
                                        <ul>
                                            <li> <a href="#."> <i class="fa fa-facebook"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-google"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-twitter"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-linkedin"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-skype"></i></a> </li>
                                        </ul>
                                    </div>


                                </div>
                            </div>

                            <!-- MAIN CONTENT -->

                            @RenderBody()


                        </div>
                    </div>
                </div>
            </div>
        </main>



    </div>
    <!-- End Page Wrapper -->
    <!-- JavaScripts -->
    <script src="~/assets/js/vendors/jquery/jquery.min.js"></script>
    <script src="~/assets/js/vendors/bootstrap.min.js"></script>
    <script src="~/assets/js/vendors/owl.carousel.min.js"></script>
    <script src="~/assets/js/vendors/jquery.isotope.min.js"></script>
    <script src="~/assets/js/main.js"></script>

    <!-- Begin Map Script-->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="~/assets/js/vendors/map.js"></script>
    @RenderSection("addjs", required: false);

</body>

</html>